steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/$_PROJECT_NAME', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$_PROJECT_ID/$_PROJECT_NAME']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '$_PROJECT_NAME', '--image', 'gcr.io/$_PROJECT_ID/$_PROJECT_NAME', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/$_PROJECT_ID/$_PROJECT_NAME
substitutions:
  _PROJECT_ID: 'flaskworldapp1-441004'
  _PROJECT_NAME: 'flaskworldapp1'
options:
  logging: CLOUD_LOGGING_ONLY
